### ISSUE TITLE
framework-wiringpi update complains about version requirement

### ISSUE THREAD

**Issue by ropy** [platformio/platform-linux_arm#1]
Hi,

First of all I would like to thank you for this awesome software.

However, after upgrading platformio from version 2.11.2 to the current stable version 3.0.1 (and even the develop version 3.0.2a1), framework-wiringpi won't update complaining about version requirements. Subsequently I can't build anymore. Please see the console output below.

I'm building on a Raspberry Pi 2b running Raspian.

`ropu@devbox:~/devel/rpi$ pio run
[Fri Sep  9 15:58:35 2016] Processing raspberrypi_2b (platform: linux_arm, build_flags: -DBCM2835 -DRH_PLATFORM=RH_PLATFORM_RASPI -Ilib/RadioHead/RHutil -I/usr/include/event2 -lpthread -std=gnu++11 -L/usr/lib/arm-linux-gnueabihf -levent -levent_core -levent_pthreads, board: raspberrypi_2b, framework: wiringpi)

PackageManager: Installing framework-wiringpi @ ~1.232.0
Downloading  [####################################]  100%  
Unpacking  [####################################]  100%  
Warning! Package Mirror: Package version 1.1.0 doesn't satisfy requirements ~1.232.0
Looking for the another mirror...
Downloading  [####################################]  100%  
Unpacking  [####################################]  100%  
Warning! Package Mirror: Package version 1.1.0 doesn't satisfy requirements ~1.232.0
Looking for the another mirror...
Downloading  [####################################]  100%  
Unpacking  [####################################]  100%  
Warning! Package Mirror: Package version 1.1.0 doesn't satisfy requirements ~1.232.0
Looking for the another mirror...
Error: Can not install 'framework-wiringpi' with version requirements '~1.232.0' for your system 'linux_armv6l'`

Best regards,
Robin

**Comment by ivankravets** [comment]
Thanks! I've just fixed package. Could you try again?

**Comment by ropy** [comment]
Perfect! 

`PackageManager: Installing framework-wiringpi @ ~1.232.0`
`Downloading  [####################################]  100%`
`Unpacking  [####################################]  100%`
`framework-wiringpi @ 1.232.0 has been successfully installed!`

That leaves me with some other errors, but those are most likely caused by the external libraries I'm using. I'm going figure that out later.

Thanks a lot.

**Comment by ivankravets** [comment]
Thanks that reported!

Happy Coding! 😊
